name: nova_hub
description: "NOVA HUB - Controle seu PC remotamente"
publish_to: 'none'
version: 2.0.0+7

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.0
  shared_preferences: ^2.2.0
  dartssh2: ^2.8.2
  xterm: ^4.0.0
  flutter_secure_storage: ^9.2.4
  webview_flutter: ^4.10.0
  flutter_markdown: ^0.7.4
  web_socket_channel: ^3.0.0
  url_launcher: ^6.3.2
  fl_chart: ^1.2.0
  flutter_local_notifications: ^18.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#020617"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/icon/app_icon_foreground.png
    - assets/vault.json
